# Generated by Django 5.2.5 on 2025-08-30 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=255, null=True)),
                ('hear_about', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('industries', models.CharField(max_length=255)),
                ('investment_range', models.CharField(max_length=50)),
                ('looking_for', models.JSONField(blank=True, default=list)),
                ('newsletter', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('comments', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StartupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=255)),
                ('heard_about', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('audience', models.TextField()),
                ('tech_component', models.TextField()),
                ('your_edge', models.TextField()),
                ('pitch_deck_url', models.CharField(max_length=255)),
                ('startup_stage', models.CharField(max_length=50)),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
                ('market_research', models.CharField(max_length=20)),
                ('business_model_mind', models.CharField(max_length=50)),
                ('working_time', models.CharField(max_length=50)),
                ('cofounder', models.CharField(max_length=20)),
                ('support_needed', models.TextField()),
                ('has_mvp', models.CharField(max_length=10)),
                ('tested_with_customers', models.CharField(max_length=10)),
                ('funding_source', models.CharField(max_length=100)),
                ('early_users', models.CharField(max_length=10)),
                ('generated_revenue', models.CharField(max_length=20)),
                ('stage3_challenges', models.TextField()),
                ('stage3_support', models.TextField()),
                ('business_model', models.TextField()),
                ('paying_customers', models.CharField(max_length=50)),
                ('annual_revenue_4', models.CharField(max_length=50)),
                ('external_funding', models.CharField(max_length=50)),
                ('acquisition_strategies', models.TextField()),
                ('team_size', models.CharField(max_length=50)),
                ('stage4_challenges', models.TextField()),
                ('stage4_support', models.TextField()),
                ('annual_revenue_5', models.CharField(max_length=50)),
                ('active_customers_5', models.CharField(max_length=50)),
                ('markets_operating', models.CharField(max_length=100)),
                ('expansion_plans', models.TextField()),
                ('stage5_challenges', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('is_onboarded', models.BooleanField(default=False)),
                ('complete_profile_submitted', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('arr', models.FloatField(blank=True, null=True, verbose_name='Annual Recurring Revenue (ARR)')),
                ('arpu', models.FloatField(blank=True, null=True, verbose_name='Average Revenue Per User (ARPU)')),
                ('monthly_burn', models.FloatField(blank=True, null=True)),
                ('cash_balance', models.FloatField(blank=True, null=True)),
                ('ltv_cac_ratio', models.FloatField(blank=True, null=True)),
                ('operating_expenses', models.FloatField(blank=True, null=True)),
                ('debt_obligations', models.TextField(blank=True, null=True)),
                ('capital_raised', models.FloatField(blank=True, null=True)),
                ('currently_raising', models.FloatField(blank=True, null=True)),
                ('equity_offered', models.FloatField(blank=True, null=True)),
                ('financial_forecast', models.FileField(blank=True, null=True, upload_to='financial_forecasts/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='startup_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CapTableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shares', models.PositiveIntegerField()),
                ('percent', models.FloatField()),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cap_table_entries', to='core.startupprofile')),
            ],
        ),
    ]
