# Generated by Django 5.0.2 on 2025-08-26 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startup_name', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=255)),
                ('heard_about', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('audience', models.TextField()),
                ('tech_component', models.TextField()),
                ('your_edge', models.TextField()),
                ('pitch_deck_url', models.CharField(max_length=255)),
                ('startup_stage', models.CharField(max_length=50)),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
                ('market_research', models.CharField(max_length=20)),
                ('business_model_mind', models.CharField(max_length=20)),
                ('working_time', models.CharField(max_length=50)),
                ('cofounder', models.CharField(max_length=20)),
                ('support_needed', models.TextField()),
                ('has_mvp', models.CharField(max_length=20)),
                ('tested_with_customers', models.CharField(max_length=20)),
                ('funding_source', models.CharField(max_length=100)),
                ('early_users', models.CharField(max_length=20)),
                ('generated_revenue', models.CharField(max_length=20)),
                ('stage3_challenges', models.TextField()),
                ('stage3_support', models.TextField()),
                ('business_model', models.TextField()),
                ('paying_customers', models.CharField(max_length=50)),
                ('annual_revenue_4', models.CharField(max_length=50)),
                ('external_funding', models.CharField(max_length=20)),
                ('acquisition_strategies', models.TextField()),
                ('team_size', models.CharField(max_length=50)),
                ('stage4_challenges', models.TextField()),
                ('stage4_support', models.TextField()),
                ('annual_revenue_5', models.CharField(max_length=50)),
                ('active_customers_5', models.CharField(max_length=50)),
                ('markets_operating', models.CharField(max_length=100)),
                ('expansion_plans', models.TextField()),
                ('stage5_challenges', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='startup_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
