# Generated by Django 5.0.2 on 2025-08-26 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startupprofile',
            name='business_model_mind',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='early_users',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='external_funding',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='has_mvp',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='startupprofile',
            name='tested_with_customers',
            field=models.CharField(max_length=10),
        ),
    ]
