# Generated by Django 5.2.5 on 2025-08-27 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_startupprofile_business_model_mind_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=150, null=True)),
                ('linkedin', models.URLField(blank=True, max_length=255, null=True)),
                ('hear_about', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=50)),
                ('industries', models.CharField(max_length=255)),
                ('investment_range', models.CharField(max_length=50)),
                ('looking_for', models.JSONField(blank=True, default=list)),
                ('newsletter', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=10)),
                ('comments', models.TextField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
