# Generated by Django 5.0.2 on 2025-08-27 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_startupprofile_business_model_mind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupprofile',
            name='is_onboarded',
            field=models.BooleanField(default=False),
        ),
    ]
