# Generated by Django 5.0.2 on 2025-09-04 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_investorinvestment_investorcompanysave'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorinvestment',
            name='equity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='investorinvestment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='investorinvestment',
            name='investor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='core.investorprofile'),
        ),
    ]
