# Generated by Django 5.2.5 on 2025-09-08 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_investorinvestment_equity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='startup_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.startupprofile')),
            ],
        ),
    ]
