# Generated by Django 5.0.2 on 2025-08-28 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_investorprofile'),
        ('core', '0003_startupprofile_is_onboarded'),
    ]

    operations = [
    ]
