# Generated by Django 5.2.5 on 2025-09-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_startupdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='investorinvestment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Active'), ('rejected', 'Rejected')], default='pending', max_length=16),
        ),
    ]
