# Generated by Django 5.0.2 on 2025-08-28 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20250828_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupprofile',
            name='arpu',
            field=models.FloatField(blank=True, null=True, verbose_name='Average Revenue Per User (ARPU)'),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='arr',
            field=models.FloatField(blank=True, null=True, verbose_name='Annual Recurring Revenue (ARR)'),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='capital_raised',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='cash_balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='currently_raising',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='debt_obligations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='equity_offered',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='financial_forecast',
            field=models.FileField(blank=True, null=True, upload_to='financial_forecasts/'),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='ltv_cac_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='monthly_burn',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='startupprofile',
            name='operating_expenses',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
