# Generated by Django 5.0.2 on 2025-08-28 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_startupprofile_arpu_startupprofile_arr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupprofile',
            name='complete_profile_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
