# Generated by Django 5.0.2 on 2025-08-29 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_startupprofile_complete_profile_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapTableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shares', models.PositiveIntegerField()),
                ('percent', models.FloatField()),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cap_table_entries', to='core.startupprofile')),
            ],
        ),
    ]
