# Generated by Django 5.2.5 on 2025-08-30 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_captableentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startupprofile',
            name='arpu',
        ),
        migrations.RemoveField(
            model_name='startupprofile',
            name='arr',
        ),
        migrations.RemoveField(
            model_name='startupprofile',
            name='capital_raised',
        ),
        migrations.RemoveField(
            model_name='startupprofile',
            name='cash_balance',
        ),
        migrations.RemoveField(
            model_name='startupprofile',
            name='complete_profile_submitted',
        ),
        migrations.RemoveField(
            model_name='startupprofile',
            name='currently_raising',
        ),
        migrations.RemoveField(
            model_name='startupprofile',
            name='debt_obligations',
        ),
        migrations.RemoveField(
            model_name='startupprofile',
            name='equity_offered',
        ),
        migrations.RemoveField(
            model_name='startupprofile',
            name='financial_forecast',
        ),
        migrations.RemoveField(
            model_name='startupprofile',
            name='ltv_cac_ratio',
        ),
        migrations.RemoveField(
            model_name='startupprofile',
            name='monthly_burn',
        ),
        migrations.RemoveField(
            model_name='startupprofile',
            name='operating_expenses',
        ),
        migrations.DeleteModel(
            name='CapTableEntry',
        ),
    ]
