# Generated by Django 5.0.2 on 2025-08-30 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_captableentry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='startupprofile',
            name='complete_profile_submitted',
        ),
        migrations.DeleteModel(
            name='CapTableEntry',
        ),
    ]
