# Generated by Django 5.0.2 on 2025-08-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_startupprofile_complete_profile_submitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='startupprofile',
            name='complete_profile_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
